name: Purge Cloudflare R2 Cache

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  purge-r2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Wrangler
        run: npm install -g wrangler

      - name: Authenticate with Wrangler
        run: wrangler whoami
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: List and delete R2 objects under fullcache/
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          export BUCKET="netflix-cache"
          wrangler r2 object list $BUCKET --json > objects.json
          
          cat objects.json | jq -r '.[] | select(.key | startswith("fullcache/")) | .key' > keys.txt

          while read -r key; do
            echo "Deleting: $key"
            wrangler r2 object delete $BUCKET "$key"
          done < keys.txt