name: Purge Cloudflare Cache

on:
  push:
    branches:
      - main

jobs:
  purge:
    name: Purge Cloudflare Edge Cache
    runs-on: ubuntu-latest

    steps:
      - name: Purge cache from Cloudflare by URL prefix
        uses: nathanvaughn/actions-cloudflare-purge@master
        with:
          cf_zone: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          cf_auth: ${{ secrets.CLOUDFLARE_API_TOKEN }}
